export { default as Header } from './Header/Header';
export { default as Home } from './Home/Home';
export { default as About } from './About/About';
export { default as Skills } from './Skills/Skills';
export { default as Services } from './Services/Services';
export { default as Qualification } from "./Qualification/Qualification";
export { default as Testimonials } from "./testimonials/Testimonials";
export { default as Contact } from "./Contact/Contact";
export { default as Footer } from "./Footer/Footer";
export { default as Top } from "./Top/Top";
export {default as Work} from "./Work/Work";